Description: >
  SageMaker Notebook Instance

Parameters:
  Identifier:
    Default: poc
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose a VPC to deploy resources in

  Subnet:
    Description: Subnet for the SageMaker instance
    Type: AWS::EC2::Subnet::Id

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub AmazonSageMaker-ExecutionRole-${Identifier}
      Path: /service-role/
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "sagemaker.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupName: !Sub SageMaker-Instance-SG-${Identifier}
      GroupDescription: For SageMaker
      SecurityGroupIngress:
      - Description: All
        CidrIp: 0.0.0.0/0
        IpProtocol: -1
        FromPort: 0
        ToPort: 65535

  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      DefaultCodeRepository: https://github.com/nclouds-code/dl-poc-notebook.git
      DirectInternetAccess: Enabled
      InstanceType: ml.t2.medium
      NotebookInstanceName: !Ref Identifier
      RoleArn: !GetAtt InstanceRole.Arn
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref Subnet
